# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX（Miuix / Compose 依赖 androidx）
android.useAndroidX=true

# 非传递 R 类
android.nonTransitiveRClass=true

# 进程内编译，避免 Kotlin daemon 写入沙箱外的目录
kotlin.compiler.execution.strategy=in-process
